fn_args_layout = "Compressed"
force_explicit_abi = false
max_width = 100
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Max"
struct_field_align_threshold = 30
enum_discrim_align_threshold = 30